--This stuff is junk - get rid of it
minetest.register_alias("xtraores_door:door_rainbow", "xtraores_rainbow:wood")
minetest.register_alias("xtraores_mblox:platinumtorch", "default:torch")
minetest.register_alias("xtraores_misc:simple_microchip", "xtraores:cobalt_ingot")
minetest.register_alias("xtraores_misc:microchip", "xtraores:geminitinum_ingot")
minetest.register_alias("xtraores_tech:xray", "default:glass")
minetest.register_alias("xtraores_tech:ropegen", "default:wood")
minetest.register_alias("xtraores_tech:rope", "wool:white")
minetest.register_alias("xtraores_tech:lonely_rope", "wool:white")
minetest.register_alias("xtraores_door:door_rainbow", "xtraores:geminitinum_ingot")
minetest.register_alias("xtraores_door:door_rainbow_a", "doors:door_wood_a")
minetest.register_alias("xtraores_door:door_rainbow_b", "doors:door_wood_b")
minetest.register_alias("xtraores:stone_with_antracite", "default:stone_with_coal")
minetest.register_alias("xtraores:antracite_lump", "default:coal_lump")
minetest.register_alias("xtraores_armor:helmet_crown", "default:gold_ingot")